from proteus import config, Model

config = config.set_xmlrpc('http://admin:admin@teffalump.com:8001/demo')

# Models
User = Model.get('res.user')
Patient = Model.get('gnuhealth.patient')
Du = Model.get('gnuhealth.du')
Alt = Model.get('gnuhealth.person_alternative_identification')
Name = Model.get('gnuhealth.person_name')
Party = Model.get('party.party')
Lang = Model.get('ir.lang')
Hp = Model.get('gnuhealth.healthprofessional')
Spec = Model.get('gnuhealth.specialty')
MSpec = Model.get('gnuhealth.hp_specialty')
Inst = Model.get('gnuhealth.institution')
Path = Model.get('gnuhealth.pathology')
TestType = Model.get('gnuhealth.lab.test_type')
Lab = Model.get('gnuhealth.lab')
Request = Model.get('gnuhealth.patient.lab.test')
Vaccine = Model.get('gnuhealth.vaccination')
Surgery = Model.get('gnuhealth.surgery')
OR = Model.get('gnuhealth.hospital.or')
Surg_Team = Model.get('gnuhealth.surgery_team')
Procedure = Model.get('gnuhealth.operation')

# Delete data
Procedure.delete(Procedure.find())
Surg_Team.delete(Surg_Team.find())
Surgery.delete(Surgery.find())
OR.delete(OR.find())
Vaccine.delete(Vaccine.find())
Lab.delete(Lab.find())
Request.delete(Request.find())
Inst.delete(Inst.find())
Du.delete(Du.find())
Patient.delete(Patient.find())
Hp.delete(Hp.find())
Party.delete(Party.find())
