class organizationType:
    contents=[{'code': 'prov',  'display': 'Healthcare Provider',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'dept', 'display': 'Hospital Department',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'icu', 'display': 'Intensive Care Unit',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'team', 'display': 'Organizational team',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'fed', 'display': 'Federal Government',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'ins', 'display': 'Insurance Company',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'edu', 'display': 'Educational Institute',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'reli', 'display': 'Religious Institution',
                'system': 'http://hl7.org/fhir/organization-type'},
            {'code': 'pharm', 'display': 'Pharmacy',
                'system': 'http://hl7.org/fhir/organization-type'}]
